Tagsegmentenhancements
cusac/mbt.guide-backend pull request #43
Opened 2020-11-04 19:49 UTC by franksmicro

Added code to update-video-segments api to normalize tags before storing in database.  Wanted to get this out there for review as soon as possible since duplicate segments are being created daily during editing.

I also updated the schema to add segmentCount field to tags, and a one-time update script to populate this field for existing data.  However, I have not yet completed the code change to populate this field in real time, so no hurry on reviewing this.

I'm still working on the code to populate segmentCount, but expect to have ready in a few days.  The one-time script to merge existing tags will likely take quite a bit longer.

2020-11-09 03:31 UTC, JKHeadley requested changes

2020-11-09 03:31 UTC, JKHeadley commented on package.json
> +    "start:local": "set NODE_ENV=local & nodemon index.js",
I assume this is required syntax for windows. I will have to test locally to see. Most likely we will need to include both with either an OS test or different command options depending on your OS.

2020-11-09 03:31 UTC, JKHeadley commented on scripts/orphan-tags.js
> +//require('dotenv').config();
Was `dotenv` not functioning correctly?

2020-11-09 03:31 UTC, JKHeadley commented on server/models/user.model.js
> +// const s3 = new AWS.S3();
We won't want to merge the commented code to master.

2020-11-09 03:31 UTC, JKHeadley commented on server/models/user.model.js
> +        // }
Same here.

2020-11-09 03:31 UTC, JKHeadley commented on server/models/user.model.js
> +        //user = await this.updateActive({ firebaseUser: result.user, user });
Same.

2020-11-09 03:31 UTC, JKHeadley commented on server/models/user.model.js
> +          email: email.toLowerCase(),
I think this is also part of the local changes to your system. If so then let's not merge this.

2020-11-09 03:31 UTC, JKHeadley commented on utilities/querytest.js
> +'use strict';
Could you add a description to what you use this test for?

2020-11-09 03:31 UTC, JKHeadley commented on utilities/querytest_save.js
> +'use strict';
Same as above, could you add a description for this?

2021-06-21 17:44 UTC, franksmicro commented
I accidentally pushed some changes that were only meant for my local machine.

The changes requested in this PR have all been implemented as part of other PRs, so this PR is now obsolete.

2021-06-21 17:46 UTC, closed without merging